language: python
sudo: false

python:
  - "3.6"
# command to install dependencies

env:
  - DJANGO_VERSION=2.1.7

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install pycodestyle

# command to run tests
script:
  - python manage.py test
  - pycodestyle --statistics -qq BookShop/__init__.py
  - pycodestyle --statistics -qq BookShop/admin.py
  - pycodestyle --statistics -qq BookShop/apps.py
  - pycodestyle --statistics -qq BookShop/models.py
  - pycodestyle --statistics -qq BookShop/tests.py
  - pycodestyle --statistics -qq BookShop/urls.py
  - pycodestyle --statistics -qq BookShop/views.py
  - pycodestyle --statistics -qq BookShopTMD
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master